spring.application.name=ActuatorTestingProject
management.endpoint.env.enabled=true
management.endpoints.jmx.exposure.include=*
server.port=1212
spring.security.user.name=Kiran
spring.security.user.password=Kiran@123